language: python
python:
  - "2.7"
install:
  - pip install tox coveralls
script:
  - tox
env:
  - TOXENV=django16
  - TOXENV=django17
  - TOXENV=django18
  - TOXENV=django19
after_success:
  - coveralls
