# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('tmdb_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[(b'movie', b'movie'), (b'series', b'series')], max_length=6)),
                ('title', models.CharField(max_length=255)),
                ('release', models.DateField()),
                ('poster_url', models.URLField()),
                ('added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
